### ISSUE TITLE
Analytics - Event logged, but value missing

### ISSUE THREAD

**Issue by natanraj** [eclipsesource/tabris-plugin-firebase#10]
### Problem description

I am using this plugin. handy. But the event is logged, not the value that we are passing is not getting logged and unable to see them in the firebase console. **Event alone is visible**.

### Expected behavior

Both event and event value should be shown in the firebase console.
### Environment

- Tabris.js version: 2.x nightly
- Device: Samsung J and Redmi Note 3
- OS: android 6.0

### Code snippet

```javascript

var gAnalytics = {};
gAnalytics.logEvent = function(pageName, eventName, value){
firebase.Analytics.analyticsCollectionEnabled = true;
firebase.Analytics.screenName = pageName;
if (value){
  firebase.Analytics.logEvent(eventName,{text:'test me'} );
}

}
module.exports = gAnalytics;


```

**Comment by mpost** [comment]
Thanks for the report. Will look into the issue.

**Comment by natanraj** [comment]
@mpost Do we have any luck on this ?

**Comment by mpost** [comment]
@natanraj In fact we looked into it and found that it works as expected. We just included the plugin in a new project and it worked as advertised. maybe your `value` in your snippet is false?

**Comment by natanraj** [comment]
@mpost i too thought so. If it is false - then event wouldn't have been logged right.  By the by i had a even used a console.log inside to ensure it reached there :-)

**Comment by mpost** [comment]
i have no idea really. Maybe you can enable the logging earlier in your app? 

```js
firebase.Analytics.analyticsCollectionEnabled = true;
```

**Comment by natanraj** [comment]
@mpost ; yes.. it is there in the same code snippet

**Comment by natanraj** [comment]
@mpost can you  please give any 'non-example' code snippet you used..

**Comment by mpost** [comment]
At first we activate analytics collection:

```js
firebase.Analytics.analyticsCollectionEnabled = true;
```

than we use it like 

```js
firebase.Analytics.screenName = 'name';
```
or
```js
firebase.Analytics.logEvent('tutorial_complete');
```

**Comment by natanraj** [comment]
Closing this
