### ISSUE TITLE
Make it possible to consume notifications in all app states and present them appropriately

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-plugin-firebase#29]
### Problem description

Current state:

* _data_ only messages don't show notification banners on iOS.

e.g. 
```
    {
      to: ...,
      data: {
        title: 'title',
        body: 'body',
        payload: {}
      }
    }    
```
* _notification_/_data_ messages show banners on iOS.
e.g. 
```
    {
      to: ...,
      data: {
        title: 'title',
        body: 'body',
        payload: {}
      },
      notification: {
        title: 'title',
        body: 'body'
      }
    }    
```
When a _data_ only message is received:

||app killed (cold start through tap on notification)|app in bg|app in fg|
|---|---|---|---|
|`"message"` event fired|_cannot launch, since no banner is shown_|✔|✔|

When a _notification_/_data_ mixed message is received:

||app killed (cold start through tap on notification)|app in bg (either opened through tap on banner or app icon)|app in fg|
|---|---|---|---|
|`"message"` event fired|✖|✖|✔|
|`launchData` set|✖|-|-|

### Expected behavior

There should be a way to show a notification banner in the system UI when:

* the app is killed
* the app is in the background

There should be a way to consume a notification in the app when:

* the app is killed and is being launched
* the app is in the background and is being launched
* the app is in the foreground

... ideally only using the `"message"` event and the `launchData` property if this is possible.

**Comment by cpetrov** [comment]
This may be helpful: https://firebase.google.com/docs/cloud-messaging/ios/receive

**Comment by patrykmol** [comment]
I have updated plugin. Hook is now fixed and `launchData` is now properly propagated. All of the mixed scenarios work in the example app.

Do note that when app is in background or when doing cold start data from regular notification will always land in `launchData`. `message` event is fired when app is in foreground.
