### ISSUE TITLE
Only use launchData for cold starts

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-plugin-firebase#31]
### Problem description

Currently, `launchData` is also being set when the app is in the background and receives a notification message with a data payload. This requires handling `launchData` extraneously by also reading it when the app comes to the foreground, although in this case the `"message"` handler could be reused.

### Expected behavior

`launchData` should only get set when the app is being cold-started and received a notification. When receiving a notification while the app is in the background, a `"message"` event should be fired.

**Comment by patrykmol** [comment]
Fixed with https://github.com/eclipsesource/tabris-plugin-firebase/commit/e3f90b04985249f3a8de84e2dad2368fe7a3118d.
