### ISSUE TITLE
Query : click on notification - how to handle it ?

### ISSUE THREAD

**Issue by natanraj** [eclipsesource/tabris-plugin-firebase#34]
on('message' - i guess it is triggered when the firebase sends notification to the OS. But if the user clicks on the notification is there any eventListener for the same?

**Comment by mpost** [comment]
Your data is contained in the [`firebase.Messaging.launchData`](https://github.com/eclipsesource/tabris-plugin-firebase/blob/master/doc/cloud-messaging.md#launchdata--object).

Also see the example: https://github.com/eclipsesource/tabris-plugin-firebase/blob/master/example/src/pages/messaging.js#L72

**Comment by natanraj** [comment]
Thanks. but how do I can make the notification sound ? It appears on the system tray. If I use 'notification' type message it doesn't set launchData variable.

**Comment by mpost** [comment]
Sounds are currently not supported but would be a useful addition in the future.

**Comment by mpost** [comment]
Closing this issue as resolved right now.

**Comment by newmediaone** [comment]
Notification sounds DO work, and I was able to customize on iOS by sending this in the payload:
"sound": "www/app/src/sounds/MYSOUNDFILE.wav",

But, I couldn't get a custom notification sound to work on Android, and would love to.  Also, setting:
"sound": "default", in the firebase push json results in the default notification sound on both iOS and Android.
