### ISSUE TITLE
launchData set with delay on cold app launch

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-plugin-firebase#41]
### Problem description

`firebase.Messaging.launchData` is not set immediately on cold app launch (app killed and being started by tapping on a notification banner), but after a delay.

### Expected behavior

`launchData` should be set even when the app is cold-launched.

### Environment

- Tabris.js version: 2.5.1
- Device: iPad A1474
- OS: iOS 11.2.2

### Code snippet

Insert the following on the top of `app.js`:
```javascript
console.log('launchData: ' + firebase.Messaging.launchData);
setTimeout(() => {
  console.log('launchData after timeout: ' + firebase.Messaging.launchData);
});
```

The timeouted `console.log` will log the expected launchData. The first `console.log` will log `undefined`.

**Comment by karolszafranski** [comment]
Tabris.js iOS platform is missing a hook to introduce a nice and clean change where possibly the issue could be fixed. If we would have a hook called "before applicationDidFinishLaunching", we could possibly put `[ESFBMessaging setLaunchData:launchOptions];` there. Of course, it's possible to do it without the hook in the comment, but it would be better to wait for the changes in the platform first.

With that change first `console.log` does print the object, and not `undefined` value.

**Comment by mpost** [comment]
Is this issue still relevant?

**Comment by anselm0** [comment]
Any progress on this?  I am currently having issues with launchData on iOS.  When user taps the notification, no data is logged on both cold and warm start (app in background) of the application.

**Comment by patrykmol** [comment]
Fixed with https://github.com/eclipsesource/tabris-plugin-firebase/commit/ad5d68876ced6990fd7a830b0448f01721ed6da9.
