### ISSUE TITLE
Add API to remove delivered notifications

### ISSUE THREAD

**Issue by patrykmol** [eclipsesource/tabris-plugin-firebase#46]
### Problem description

Currently it is not possible to remove delivered notifications through an API.

### Expected behavior

Developer should be able to remove delivered notifications.

We should provide an API that will allow to remove specific notifications.

**Comment by patrykmol** [comment]
On iOS this will have to an iOS 10+ feature. Following method can be used to remove notifications: https://developer.apple.com/documentation/usernotifications/unusernotificationcenter/1649517-removependingnotificationrequest?language=objc. It accepts and array of strings which are identifiers for notifications to be removed. This identifier come from native notification object but they are not passed to JS side currently. For iOS I would have to add this identifier to notification data before sending it to JS. This will allow JS developer to specify which notification he wants to remove. I would suggest `iosIdentifier` as a key for this identifier.

**Comment by patrykmol** [comment]
After some discussion we have agreed to implement `getAll` and `clearAll` methods that will be available on `pendingMessages` object. `pendingMessages` will be a property on `Messaging` object.

**Comment by mpost** [comment]
The `pendingMessages` have been implemented on the `2.x` and `master` branch.
