### ISSUE TITLE
"message" fired redundantly when "launchData" is set

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-plugin-firebase#60]
### Problem description

The `"message"` event is fired even when `launchData` is set due to a cold app launch (app not running and being launched by tapping on a notification banner) on iOS with the same notification data.

### Expected behavior

No `"message"` event should be redundantly fired when `launchData` has been set due to a cold launch.

### Environment

- Tabris.js version: 2.6.1
- Device: iPhone 6
- OS: 12.0

### Code snippet

```javascript
setTimeout(() => { // workaround for #41
  console.log('launchData: ' + JSON.stringify(firebase.Messaging.launchData));
});
firebase.Messaging.on({message: ({data}) => console.log('"message" data: ' + JSON.stringify(data))});
```

**Comment by patrykmol** [comment]
Fixed with https://github.com/eclipsesource/tabris-plugin-firebase/commit/29baffa67c5ef817c994600a2d4313a4e63dc098.
