### ISSUE TITLE
Question: null returned on token

### ISSUE THREAD

**Issue by natanraj** [eclipsesource/tabris-plugin-firebase#7]
I am using this plugin on my app.

There are no build errors, exception or failures.

In some devices i am seeing this statement is assigning null to pushToken variable

`var pushToken = firebase.Messaging.token;`

Any idea what could be the reason ?

**Comment by natanraj** [comment]
My config.xml is like this : 
`<plugin name="tabris-plugin-firebase" spec="https://github.com/eclipsesource/tabris-plugin-firebase.git#3fa165fe072752391ad899716073a210e1bd63be" />`
per recommendation from someone in our tabris.js team for an issue

**Comment by mpost** [comment]
In general there should always be a token. Is it maybe on an emulator without Google Play Services? Is the token available after little timeout? eg a few seconds?

**Comment by natanraj** [comment]
@mpost I dont know because it is in production. So i think i even don't know how to simulate even if my timeout fix will work ?

By the by the cordova implementation is usually a callback. Here it is a return. How quickly a the device returns a token determines if it is NULL or token. Any thoughts ?

**Comment by mpost** [comment]
@natanraj If there is no token available yet you can always listen for the `change:token` event as shown in the example: https://github.com/eclipsesource/tabris-plugin-firebase/blob/master/example/src/pages/messaging.js#L29

**Comment by mpost** [comment]
Not that we will rename the `change:token` event to  `tokenChanged` soon to be in line with the upcoming Tabris.js 2.0 release.

**Comment by natanraj** [comment]
Thanks @mpost ; what is the instanceId listener for ? (Forgive my fcm knowledge)

**Comment by mpost** [comment]
You can reset the instance id, which will create a new one and fire the listener. https://github.com/eclipsesource/tabris-plugin-firebase#resetinstanceid

**Comment by mpost** [comment]
Closing as resolved. Please reopen if you have any more problems.
