### ISSUE TITLE
Casting issue - plugins > Analytics.java

### ISSUE THREAD

**Issue by natanraj** [eclipsesource/tabris-plugin-firebase#8]
### Problem description

logEvent is unable to log any event with object having integer value in key value pair.

### Expected behavior

 Analytics.logEvent should accept all basic value types 

### Environment

- Tabris.js version: nightly
- Device: All devices
- OS: Android 6

### Code snippet

```javascript
// none.
analytics.logEvent('myScreen', 'myEvent', {id:1100});
```
console.error -- couldn't call method logEvent... Reason java.lang.Integer cannot be cast to java.lang.Long

**Comment by mpost** [comment]
Thanks for the heads-up. We have fixed the issue. Please check again with the latest version.
