### ISSUE TITLE
Launchdata / data messages in background not working

### ISSUE THREAD

**Issue by 3to1null** [eclipsesource/tabris-plugin-firebase#9]
I'm sending a data message using `pyfcm`:
```
from pyfcm import FCMNotification
push_service = FCMNotification(api_key="*api-key*")

data_message = {
    "payload" : "test"
}


token = "*device token*"
result = push_service.notify_single_device(registration_id=token, data_message=data_message)
```
Firebase code in my app:
```
console.log(firebase.Messaging.token);
console.log('launched with:' + JSON.stringify(firebase.Messaging.launchData));
firebase.Messaging.on('message',
    ({data}) => {
        localStorage.setItem('test', JSON.stringify(data))
        console.log(data)
    }
);
```
When the app is running in the foreground everything works as expected, I just can't get the data of messages sent while the app wasn't running, or backgrounded.

**Comment by mpost** [comment]
Please make sure that you are creating a "data" notification as outlines here: https://github.com/eclipsesource/tabris-plugin-firebase/blob/master/doc/cloud-messaging.md#send-message-with-notification-from-server

**Comment by mpost** [comment]
Closing this as resolved. Please reopen if you still have problems.
